[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
#ctrlc = "3.0"
shared = { version = "0.1.0", path = "../shared" }

[[bin]]
name = "client"
path = "client.rs"
