name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-server:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Build Server
      working-directory: ./server
      run: cargo build --verbose
    - name: Run Server Tests
      working-directory: ./server
      run: cargo test --verbose

  build-client:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Build Client
      working-directory: ./client
      run: cargo build --verbose
    - name: Run Client Tests
      working-directory: ./client
      run: cargo test --verbose
